[package]
name = "parity-tokio-ipc"
version = "0.1.5"
authors = ["NikVolf <nikvolf@gmail.com>"]

[dependencies]
tokio-uds = "0.2"
tokio-named-pipes = { version = "0.2", git = "https://github.com/poanetwork/tokio-named-pipes" }
futures = "0.1"
tokio = "0.1"
rand = "0.3"
mio-named-pipes = { git = "https://github.com/alexcrichton/mio-named-pipes" }
miow = "0.3.2"
log = "*"
bytes = "0.4"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winbase", "winnt", "accctrl", "aclapi", "securitybaseapi", "minwinbase", "winbase"] }
